site_name: py_load_opentargets
theme:
  name: material
repo_url: https://github.com/ohdsi/py_load_opentargets
repo_name: ohdsi/py_load_opentargets

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Vignette: vignette.md
  - Configuration: configuration.md
  - Architecture: architecture.md
  - API Reference: api_reference.md
