# Default configuration for the Open Targets data loader.
# Users can override these settings by creating their own config.toml.

[source]
# Base URLs for discovering and downloading Open Targets data.
# GCS is used for high-speed downloads, FTP is used for version discovery.
gcs_base_url = "gs://open-targets/platform/"
ftp_host = "ftp.ebi.ac.uk"
ftp_path = "/pub/databases/opentargets/platform/"

# Definitions for each dataset to be loaded.
# Each dataset needs a 'primary_key' list for the merge (UPSERT) operation.
# An optional 'final_table_name' can be provided to override the default,
# which is the dataset name itself (with '-' replaced by '_').
[datasets]

[datasets.targets]
primary_key = ["id"]

[datasets.diseases]
primary_key = ["id"]

[datasets.drugs]
# The 'id' column for drugs is the ChEMBL ID.
primary_key = ["id"]

[datasets.evidence]
# Each evidence string has a unique ID.
primary_key = ["id"]

[datasets.molecule]
primary_key = ["id"]
final_table_name = "molecule"

[datasets.mousePhenotypes]
primary_key = ["targetId", "diseaseId"]
final_table_name = "mouse_phenotypes"

[datasets.associationByDatasourceDirect]
primary_key = ["targetId", "diseaseId", "datasourceId"]
final_table_name = "association_direct_by_datasource"

[datasets.associationByDatasourceIndirect]
primary_key = ["targetId", "diseaseId", "datasourceId"]
final_table_name = "association_indirect_by_datasource"

[datasets.associationByOverallDirect]
primary_key = ["targetId", "diseaseId"]
final_table_name = "association_direct_overall"

[datasets.associationByOverallIndirect]
primary_key = ["targetId", "diseaseId"]
final_table_name = "association_indirect_overall"
